// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HRServiceTest.PersonInfoService
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class 取得人員資訊Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "取得人員資訊.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "取得人員資訊", "\tIn order to 可以找到人員資訊\r\n\tAs a 人資人員\r\n\tI want to 取得人員資訊清單", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "取得人員資訊")))
            {
                HRServiceTest.PersonInfoService.取得人員資訊Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("取得人員資訊，欄位需要有員工編號、姓名、部門名稱、職稱")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "取得人員資訊")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("取得人員資訊")]
        public virtual void 取得人員資訊欄位需要有員工編號姓名部門名稱職稱()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("取得人員資訊，欄位需要有員工編號、姓名、部門名稱、職稱", new string[] {
                        "取得人員資訊"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Empno",
                        "Name",
                        "Dpt",
                        "JobTitle"});
            table1.AddRow(new string[] {
                        "A01",
                        "陳怡臻",
                        "0001",
                        "創辦人"});
#line 8
 testRunner.Given("人員為\"PersonModel\"的資料", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Dpt",
                        "Name"});
            table2.AddRow(new string[] {
                        "0001",
                        "創辦室"});
#line 11
 testRunner.And("部門為\"DepartMentModel\"的資料", ((string)(null)), table2, "And ");
#line 14
 testRunner.When("取得人員資訊", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Empno",
                        "UserName",
                        "DptName",
                        "JobTitle"});
            table3.AddRow(new string[] {
                        "A01",
                        "陳怡臻",
                        "創辦室",
                        "創辦人"});
#line 15
 testRunner.Then("人員資訊取得為\"PersonInfo\"的資料", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("取得人員資訊，依員工編號排序")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "取得人員資訊")]
        public virtual void 取得人員資訊依員工編號排序()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("取得人員資訊，依員工編號排序", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Empno",
                        "Name",
                        "Dpt",
                        "JobTitle"});
            table4.AddRow(new string[] {
                        "A02",
                        "龔柔心",
                        "0002",
                        "研究員"});
            table4.AddRow(new string[] {
                        "A01",
                        "陳怡臻",
                        "0001",
                        "創辦人"});
            table4.AddRow(new string[] {
                        "A03",
                        "林智仁",
                        "0002",
                        "研究經理"});
#line 20
 testRunner.Given("人員為\"PersonModel\"的資料", ((string)(null)), table4, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Dpt",
                        "Name"});
            table5.AddRow(new string[] {
                        "0001",
                        "創辦室"});
            table5.AddRow(new string[] {
                        "0002",
                        "研究室"});
#line 25
 testRunner.And("部門為\"DepartMentModel\"的資料", ((string)(null)), table5, "And ");
#line 29
 testRunner.When("取得人員資訊", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Empno",
                        "UserName",
                        "DptName",
                        "JobTitle"});
            table6.AddRow(new string[] {
                        "A01",
                        "陳怡臻",
                        "創辦室",
                        "創辦人"});
            table6.AddRow(new string[] {
                        "A02",
                        "龔柔心",
                        "研究室",
                        "研究員"});
            table6.AddRow(new string[] {
                        "A03",
                        "林智仁",
                        "研究室",
                        "研究經理"});
#line 30
 testRunner.Then("人員資訊取得為\"PersonInfo\"的資料", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
